AWSTemplateFormatVersion: "2010-09-09"
Description: "Template of a general purpose AWS Backup settings"

# ============================================================#
# Parameters to be input from console
# ============================================================#
Parameters:
  MyBackupName:
    Description: Backup plan name
    Type: String
    Default: ''
  Cron:
    Description: Time to do backup(cron)
    Type: String
    Default: cron(0 18 * * ? *)
  TagKey:
    Description: TagKey for backup
    Type: String
    Default: ''
  TagValue:
    Description: TagValue for backup
    Type: String
    Default: ''


# ============================================================#
# Resources to be created from this template
# ============================================================#
Resources:
  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Sub ${MyBackupName}-vault

  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties: 
      BackupPlan: 
        BackupPlanName: !Ref MyBackupName
        BackupPlanRule: 
          - RuleName: !Sub ${MyBackupName}-rule
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: !Ref Cron
            CompletionWindowMinutes: 300
            StartWindowMinutes: 60
            Lifecycle:
              DeleteAfterDays: 14

  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: !Ref MyBackupName
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole"
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: !Ref TagKey
           ConditionValue: !Ref TagValue